name: Verify MSRV

on:
  push:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR
  pull_request:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install cargo-msrv
        run: cargo binstall cargo-msrv --no-confirm
      - name: Verify MSRV
        run: cargo msrv verify