name: cargo check

on:
  push:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR
  pull_request:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Run cargo check with all features, no features, default features, and each individual feature
        run: cargo hack check --each-feature --optional-deps