name: Test

on:
  push:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR
  pull_request:
    branches-ignore:
      - master # master is a protected branch so tests will be run when we create a PR

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        run: rustup install stable
      - name: Run unit tests
        # NOTE: consider using https://github.com/frewsxcv/cargo-all-features, because all features != their arbitrary combinations
        run: cargo test --lib
  doc_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable Rust
        run: rustup install stable
      - name: Run doc tests
        # NOTE: consider using https://github.com/frewsxcv/cargo-all-features, because all features != their arbitrary combinations
        run: cargo test --doc
  test_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust
        run: rustup install nightly
      - name: Set nightly as default
        run: rustup default nightly
      - name: Run all unit tests
        run: cargo test --all-features --lib
